### ISSUE TITLE
Divide by zero error encountered in file mi_pgd_rand.py

### ISSUE THREAD

**Issue by CNOCycle** [tianzheng4/Distributionally-Adversarial-Attack#1]
Hi authors,

I'm verifying my model's robustness by the attacks in the repository.

But It reports a `divide by zero error` in following line

https://github.com/tianzheng4/Distributionally-Adversarial-Attack/blob/0f119905caa5be72799929ae0725c6923838bab3/mnist_challenge-master/mi_pgd_rand.py#L64

Adding a small epsilon may solve this issue.

**Comment by tianzheng4** [comment]
hi, thanks for pointing out the issue. Normally, at least for all the models I verified, there is no zero grad. so I didnt consider this issue.
